"""initial

Revision ID: 9059c27f6f05
Revises: 
Create Date: 2023-05-17 16:08:31.177843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=320), nullable=False),
    sa.Column('question', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.String(length=320), nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), nullable=False),
    sa.UniqueConstraint('answer'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    # ### end Alembic commands ###
